# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, 'Queued'), (1, 'In Process'), (2, 'Complete'), (3, 'Unavailable'), (4, 'Failure')], default=0, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('screen_name', models.CharField(max_length=50, unique=True, verbose_name='Screen name')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('profile_image_url', models.URLField(max_length=300, null=True, verbose_name='Image')),
                ('followers_count', models.PositiveIntegerField(default=0, verbose_name='Followers')),
                ('friends_count', models.PositiveIntegerField(default=0, verbose_name='Friends')),
            ],
            options={
                'db_table': 'twitter_profile',
            },
        ),
    ]
